set shiftwidth=2
set tabstop=2
set softtabstop=2
set expandtab

set autoindent
set smartindent

" Ouvre les split window vers le bas
" Hauteur de 12 lignes
set splitbelow
set termwinsize=12x0

"Use 24-bit (true-color) mode in Vim/Neovim when outside tmux.
"If you're using tmux version 2.2 or later, you can remove the outermost $TMUX check and use tmux's 24-bit color support
"(see < http://sunaku.github.io/tmux-24bit-color.html#usage > for more information.)
if (empty($TMUX))
  if (has("nvim"))
    "For Neovim 0.1.3 and 0.1.4 < https://github.com/neovim/neovim/pull/2198 >
    let $NVIM_TUI_ENABLE_TRUE_COLOR=1
  endif
  "For Neovim > 0.1.5 and Vim > patch 7.4.1799 < https://github.com/vim/vim/commit/61be73bb0f965a895bfb064ea3e55476ac175162 >
  "Based on Vim patch 7.4.1770 (`guicolors` option) < https://github.com/vim/vim/commit/8a633e3427b47286869aa4b96f2bfc1fe65b25cd >
  " < https://github.com/neovim/neovim/wiki/Following-HEAD#20160511 >
  if (has("termguicolors"))
    set termguicolors
  endif
endif

colorscheme onedark 
syntax on
set showmatch
" set relativenumber
set number
" set cursorline

" for statusbar plugin
set laststatus=2
let g:lightline = {
  \ 'colorscheme': 'one',
  \ }
set noshowmode

" ======= ONE DARK INSTRUCTIONS =======
" URL
" https://github.com/joshdick/onedark.vim
" INSTRUCTIONS
" Placer colors/onedark.vim dans ~/.vim/colors et autoload/onedark.vim dans ~/.vim/autoload

" ======= VIM AUTOCOMPLETION ======
" Définition des chemins de recherche pour gf, :find, et la complétion
if has('win32')
  " Windows : adapter ces chemins à ta version de Visual Studio et SDK
  " Exemples pour VS 2019 / Windows 10 SDK
  set path=.,,
  let s:msvc_ver = '14.29.30133'       " version de MSVC (vérifie le dossier)
  let s:win_sdk = '10.0.19041.0'       " version du Windows SDK
  " Ajoute les dossiers d'include s'ils existent
  if isdirectory('C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/' . s:msvc_ver . '/include')
    let &path .= ',C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/' . s:msvc_ver . '/include'
  endif
  if isdirectory('C:/Program Files (x86)/Windows Kits/10/Include/' . s:win_sdk . '/ucrt')
    let &path .= ',C:/Program Files (x86)/Windows Kits/10/Include/' . s:win_sdk . '/ucrt'
  endif
  " Tu peux aussi utiliser la variable d'environnement INCLUDE si elle est définie
  if !empty($INCLUDE)
    for incdir in split($INCLUDE, ';')
      let &path .= ',' . substitute(incdir, '\', '/', 'g')
    endfor
  endif

elseif has('macunix')
  " macOS : chemins pour Xcode Command Line Tools
  set path=.,,/usr/local/include,/usr/include,/opt/homebrew/include
  " Récupération dynamique du SDK actif via xcrun (si disponible)
  if executable('xcrun')
    let s:mac_sdk = system('xcrun --show-sdk-path 2>/dev/null')
    if v:shell_error == 0
      let s:mac_sdk = substitute(s:mac_sdk, '\n', '', '') . '/usr/include'
      let &path .= ',' . s:mac_sdk
    endif
  endif

else
  " Linux et autres Unix
  set path=.,,/usr/include,/usr/local/include
  " Ajoute également les includes spécifiques à l'architecture si présents
  if isdirectory('/usr/include/x86_64-linux-gnu')
    let &path .= ',/usr/include/x86_64-linux-gnu'
  endif
endif
